#!/bin/sh -e
# Copyright (c) 2014 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This adds support for Chromebook keyboard special keys.
#
# For example, we map Search+arrows to Page Up/Down/Home/End. This is
# done at the browser level in Chromium OS (i.e., not at the hardware
# or keymap level).
#
# The mapping of Search+F1-F10 is reversed compared to Chromium OS:
# Pressing the back key still produces F1, Search+F1 is required to
# generate XF86Back.
#
# We do this by adding an overlay, and using Super_L (Search key) as
# the overlay latch.
#
# An additional mapping is needed to make sure that Super_R is not
# sent when the Search key is released (this is a little strange,
# and I'm not sure why this happens).

REQUIRES='x11'
DESCRIPTION='Adds support for Chromebook keyboard special keys.'

#. "${TARGETSDIR:="$PWD"}/common"

### Append to prepare.sh:
#if [ "${DISTROAKA:-"$DISTRO"}" = 'debian' ]; then
    # Make sure we start from a fresh package
    apt-mark unhold xkb-data || true 2>/dev/null
    apt-get -y install --reinstall xkb-data
#fi

XKBROOT='/usr/share/X11/xkb'
XKBROOTTMP="`mktemp -d crouton-xkb.XXXXXX --tmpdir=/tmp`"
#addtrap "rm -rf --one-file-system '$XKBROOTTMP'"
mkdir -p "$XKBROOTTMP/compat" "$XKBROOTTMP/symbols" "$XKBROOTTMP/rules"

cat > "$XKBROOTTMP/compat/chromebook" <<END
// Overlay1_Enable is a latch key for overlay1

default partial xkb_compatibility "overlay"  {
    interpret Overlay1_Enable+AnyOfOrNone(all) {
        action= SetControls(controls=Overlay1);
    };
};
END

cat > "$XKBROOTTMP/symbols/chromebook" <<END
// This mapping assumes that inet(evdev) will also be sourced
partial
xkb_symbols "overlay" {
    key <LWIN> { [ Overlay1_Enable ], overlay1=<LWIN> };

    key <AB09> { overlay1=<INS> };

    key <LEFT> { overlay1=<HOME> };
    key <RGHT> { overlay1=<END> };
    key <UP>   { overlay1=<PGUP> };
    key <DOWN> { overlay1=<PGDN> };

    key <FK01> { overlay1=<I247> };
    key <I247> { [ XF86Back ] };
    key <FK02> { overlay1=<I248> };
    key <I248> { [ XF86Forward ] };
    key <FK03> { overlay1=<I249> };
    key <I249> { [ XF86Reload ] };
    key <FK04> { overlay1=<I235> }; // XF86Display
    key <FK05> { overlay1=<I250> };
    key <I250> { [ XF86ApplicationRight ] };
    key <FK06> { overlay1=<I232> }; // XF86MonBrightnessDown
    key <FK07> { overlay1=<I233> }; // XF86MonBrightnessUp
    key <FK08> { overlay1=<MUTE> };
    key <FK09> { overlay1=<VOL-> };
    key <FK10> { overlay1=<VOL+> };

    key <AE01> { overlay1=<FK01> };
    key <AE02> { overlay1=<FK02> };
    key <AE03> { overlay1=<FK03> };
    key <AE04> { overlay1=<FK04> };
    key <AE05> { overlay1=<FK05> };
    key <AE06> { overlay1=<FK06> };
    key <AE07> { overlay1=<FK07> };
    key <AE08> { overlay1=<FK08> };
    key <AE09> { overlay1=<FK09> };
    key <AE10> { overlay1=<FK10> };
    key <AE11> { overlay1=<FK11> };
    key <AE12> { overlay1=<FK12> };
    key <BKSP> { overlay1=<DELE> };

    // uncomment the below 2 lines to map search+LALT or RALT to CAPS
    // key <LALT> { overlay1=<CAPS> };
    // key <RALT> { overlay1=<CAPS> };

    // For some strange reason, some Super_R events are triggered when
    // the Search key is released (i.e. with overlay on).
    // This maps RWIN to a dummy key (<I253>), to make sure we catch it.
    key <RWIN> { [ NoSymbol ], overlay1=<I253> };

    // Map dummy key to no symbol
    key <I253> { [ NoSymbol ] };

    // For all other "normal" keys (alphanumeric, symbols, but not modifiers
    // such as Shift, Alt, Ctrl), map Search+key to mod4+key
    // Because of the way XKB overlays work, we need to bounce off another
    // keycode (we use I208-253 here)
    key <ESC> { overlay1= <I208> };
    key <I208> { actions[Group1]= [ Redirect(keycode=<ESC>, modifiers=mod4) ] };
    key <BKSL> { overlay1= <I209> };
    key <I209> { actions[Group1]= [ Redirect(keycode=<BKSL>, modifiers=mod4) ] };
    key <AB01> { overlay1= <I210> };
    key <I210> { actions[Group1]= [ Redirect(keycode=<AB01>, modifiers=mod4) ] };
    key <AB02> { overlay1= <I211> };
    key <I211> { actions[Group1]= [ Redirect(keycode=<AB02>, modifiers=mod4) ] };
    key <AB03> { overlay1= <I212> };
    key <I212> { actions[Group1]= [ Redirect(keycode=<AB03>, modifiers=mod4) ] };
    key <AB04> { overlay1= <I213> };
    key <I213> { actions[Group1]= [ Redirect(keycode=<AB04>, modifiers=mod4) ] };
    key <AB05> { overlay1= <I214> };
    key <I214> { actions[Group1]= [ Redirect(keycode=<AB05>, modifiers=mod4) ] };
    key <AB06> { overlay1= <I215> };
    key <I215> { actions[Group1]= [ Redirect(keycode=<AB06>, modifiers=mod4) ] };
    key <AB07> { overlay1= <I216> };
    key <I216> { actions[Group1]= [ Redirect(keycode=<AB07>, modifiers=mod4) ] };
    key <AB08> { overlay1= <I217> };
    key <I217> { actions[Group1]= [ Redirect(keycode=<AB08>, modifiers=mod4) ] };
    key <AB10> { overlay1= <I218> };
    key <I218> { actions[Group1]= [ Redirect(keycode=<AB10>, modifiers=mod4) ] };
    key <TAB> { overlay1= <I219> };
    key <I219> { actions[Group1]= [ Redirect(keycode=<TAB>, modifiers=mod4) ] };
    key <AD01> { overlay1= <I220> };
    key <I220> { actions[Group1]= [ Redirect(keycode=<AD01>, modifiers=mod4) ] };
    key <AD02> { overlay1= <I221> };
    key <I221> { actions[Group1]= [ Redirect(keycode=<AD02>, modifiers=mod4) ] };
    key <AD03> { overlay1= <I222> };
    key <I222> { actions[Group1]= [ Redirect(keycode=<AD03>, modifiers=mod4) ] };
    key <AD04> { overlay1= <I223> };
    key <I223> { actions[Group1]= [ Redirect(keycode=<AD04>, modifiers=mod4) ] };
    key <AD05> { overlay1= <I224> };
    key <I224> { actions[Group1]= [ Redirect(keycode=<AD05>, modifiers=mod4) ] };
    key <AD06> { overlay1= <I225> };
    key <I225> { actions[Group1]= [ Redirect(keycode=<AD06>, modifiers=mod4) ] };
    key <AD07> { overlay1= <I226> };
    key <I226> { actions[Group1]= [ Redirect(keycode=<AD07>, modifiers=mod4) ] };
    key <AD08> { overlay1= <I227> };
    key <I227> { actions[Group1]= [ Redirect(keycode=<AD08>, modifiers=mod4) ] };
    key <AD09> { overlay1= <I228> };
    key <I228> { actions[Group1]= [ Redirect(keycode=<AD09>, modifiers=mod4) ] };
    key <AD10> { overlay1= <I229> };
    key <I229> { actions[Group1]= [ Redirect(keycode=<AD10>, modifiers=mod4) ] };
    key <AD11> { overlay1= <I230> };
    key <I230> { actions[Group1]= [ Redirect(keycode=<AD11>, modifiers=mod4) ] };
    key <AD12> { overlay1= <I231> };
    key <I231> { actions[Group1]= [ Redirect(keycode=<AD12>, modifiers=mod4) ] };
    key <RTRN> { overlay1= <I234> };
    key <I234> { actions[Group1]= [ Redirect(keycode=<RTRN>, modifiers=mod4) ] };
    key <AC01> { overlay1= <I235> };
    key <I235> { actions[Group1]= [ Redirect(keycode=<AC01>, modifiers=mod4) ] };
    key <AC02> { overlay1= <I236> };
    key <I236> { actions[Group1]= [ Redirect(keycode=<AC02>, modifiers=mod4) ] };
    key <AC03> { overlay1= <I237> };
    key <I237> { actions[Group1]= [ Redirect(keycode=<AC03>, modifiers=mod4) ] };
    key <AC04> { overlay1= <I238> };
    key <I238> { actions[Group1]= [ Redirect(keycode=<AC04>, modifiers=mod4) ] };
    key <AC05> { overlay1= <I239> };
    key <I239> { actions[Group1]= [ Redirect(keycode=<AC05>, modifiers=mod4) ] };
    key <AC06> { overlay1= <I240> };
    key <I240> { actions[Group1]= [ Redirect(keycode=<AC06>, modifiers=mod4) ] };
    key <AC07> { overlay1= <I241> };
    key <I241> { actions[Group1]= [ Redirect(keycode=<AC07>, modifiers=mod4) ] };
    key <AC08> { overlay1= <I242> };
    key <I242> { actions[Group1]= [ Redirect(keycode=<AC08>, modifiers=mod4) ] };
    key <AC09> { overlay1= <I243> };
    key <I243> { actions[Group1]= [ Redirect(keycode=<AC09>, modifiers=mod4) ] };
    key <AC10> { overlay1= <I244> };
    key <I244> { actions[Group1]= [ Redirect(keycode=<AC10>, modifiers=mod4) ] };
    key <AC11> { overlay1= <I245> };
    key <I245> { actions[Group1]= [ Redirect(keycode=<AC11>, modifiers=mod4) ] };
    key <TLDE> { overlay1= <I246> };
    key <I246> { actions[Group1]= [ Redirect(keycode=<TLDE>, modifiers=mod4) ] };
    key <LSGT> { overlay1= <I251> };
    key <I251> { actions[Group1]= [ Redirect(keycode=<LSGT>, modifiers=mod4) ] };
};
END

awk '
# default: print line
1

# rules/base.ml1_c.part
/^! model[ \t]*layout\[1\][ \t]*=[ \t]*compat$/{
    found[1]++;
    print "  chromebook	*		=	complete+chromebook"
}

# rules/base.ml_c.part
/^! model[ \t]*layout[ \t]*=[ \t]*compat$/{
    found[2]++;
    print "  chromebook	*		=	complete+chromebook"
}

# rules/evdev.m_s.part
/^! model[ \t]*=[ \t]*symbols$/{
    found[3]++;
    print "  chromebook	=   +inet(evdev)+chromebook(overlay)"
}

END {
    for (i = 1; i <= 3; i++) {
        if (found[i] != 1) {
            print "Error: " FILENAME ": rule " i ": applied " found[i] " times" > "/dev/stderr"
            exit 1
        }
    }
}
' "$XKBROOT/rules/evdev" > "$XKBROOTTMP/rules/evdev"

# rules/base.xml.in
awk '
# default: print line
1

/^.*<modelList>$/{
    found++;
    print "    <model>";
    print "      <configItem>";
    print "        <name>chromebook</name>";
    print "        <description>Chromebook</description>";
    print "        <vendor>Google</vendor>";
    print "      </configItem>";
    print "    </model>"
}

END {
    if (found != 1) {
        print "Error: " FILENAME ": rule applied " found " times" > "/dev/stderr"
        exit 1
    }
}
' "$XKBROOT/rules/evdev.xml" > "$XKBROOTTMP/rules/evdev.xml"

awk '
# default: print line
1

/^! model$/{
    found++;
    print "  chromebook      Chromebook"
}

END {
    if (found != 1) {
        print "Error: " FILENAME ": rule applied " found " times" > "/dev/stderr"
        exit 1
    }
}
' "$XKBROOT/rules/evdev.lst" > "$XKBROOTTMP/rules/evdev.lst"

# Apply the modifications
cp -a "$XKBROOTTMP"/* "$XKBROOT"/

#if [ "${DISTROAKA:-"$DISTRO"}" = 'debian' ]; then
    # Hold xkb-data, so that it does not get updated
    apt-mark hold xkb-data
#fi
